config/routes.rb
Rails.application.routes.draw do
 
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/friends', to: 'static_pages#friends'
  get '/signup', to: 'users#new'
  get '/newList', to: 'lists#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  delete '/deleteItem', to: 'items#destroy'
  delete '/deleteList', to: 'lists#destroy'
  get '/shareList', to: 'lists#share'
  get '/addList', to: 'lists#add'
 
  resources :users
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :list
	validates :name, presence: true, length: { maximum: 30 }
end

app/models/list.rb
class List < ApplicationRecord
	has_and_belongs_to_many :users
	has_many :items
	default_scope -> { order(created_at: :desc) }
	validates :name, presence: true, length: { maximum: 30 }
end

app/models/user.rb
class User < ApplicationRecord
	has_and_belongs_to_many :lists, dependent: :destroy
	attr_accessor :remember_token

	# the self is optional here because it is inside the User model, so email = email.downcase is the same thing
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 30 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
	    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                  BCrypt::Engine.cost
	    BCrypt::Password.create(string, cost: cost)
  	end

	  # Returns a random token.
  	def User.new_token
	    SecureRandom.urlsafe_base64
  	end

  	# Remembers a user in the database for use in persistent sessions.

  	def remember
	    self.remember_token = User.new_token
	    update_attribute(:remember_digest, User.digest(remember_token))
  	end

  	def authenticated?(remember_token)return false if remember_digest.nil?
  		
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end

  	# Forgets a user.
  	def forget
    	update_attribute(:remember_digest, nil)
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		redirect_to :back
	end

	private

	def items_params
      params.require(:list).permit(:id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]

	def show
  		@list = List.find(params[:id])
  		@users = @list.users.paginate(page: params[:page])
  		@items = Item.all.where('list_id =' + params[:id].to_s)
  	end

  	def new
  		@list = List.new
  		
  	end

	def create
		@list = List.new
		@list.name = list_params[:name]
		@user = User.find(@current_user.id)
		@user.lists << @list
		@user.save		
		@list.save
  		redirect_to @list
	end

	def edit
  		@list = List.find(params[:id])
	end

	def update
  	@list = List.find(params[:id])
  	@item = Item.new
  	@item.name = list_params[:name]
  	@item.list_id = params[:id]
  	@item.save
  	redirect_to :back
	end

	def share
		@list = List.find(params[:id])
		@people = User.all
	end

  def add
    @list = List.find(params[:id])
    if User.find(params[:userid]).lists.include? @list
      redirect_to :back
      return
    else
      User.find(params[:userid]).lists << @list
      redirect_to :back
    end
  end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to :back
	end

	private

    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

   def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end

  def about
  end

  def friends
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
 
  def show
  	@user = User.find(params[:id])
  	@lists = @user.lists.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


   private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
    	session[:user_id] = user.id
	end

	# Remembers a user in a persistent session.
  	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

  	def current_user?(user)
    	user == current_user
  	end

	def current_user
    	if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
      		user = User.find_by(id: user_id)
	      	if user && user.authenticated?(cookies[:remember_token])
		        log_in user
		        @current_user = user
      		end
    	end
  	end

  	def logged_in?
    	!current_user.nil?
  	end

  	# Forgets a persistent session.
  	def forget(user)
	    user.forget
	    cookies.delete(:user_id)
	    cookies.delete(:remember_token)
  	end

  	def log_out
  		forget(current_user)
    	session.delete(:user_id)
    	@current_user = nil
  	end

  	def redirect_back_or(default)
	    redirect_to(session[:forwarding_url] || default)
	    session.delete(:forwarding_url)
  	end

  	def store_location
    	session[:forwarding_url] = request.original_url if request.get?
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-inverse">
  <div class="container">
    <%= link_to "List Share", current_user, id: "navTitle" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>List App <%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	 <%= render 'layouts/header' %>
   <div class='container'>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/lists/_item_form.html.erb
<%= form_for(@list) do |f| %>
  
  <%= f.text_field :name, class: 'itemAdd', value: '' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/lists/new.html.erb
<% provide(:title, 'New List') %>



<%= form_for(@list) do |f| %>
  
  <%= f.text_field :name, class: 'itemAdd', value: '' %>

  <%= f.submit 'Create List', class: "btn btn-primary" %>

<% end %>

app/views/lists/share.html.erb
<h1>Share</h1>


<ul class="lists">
	<% @people.each do |user|%>
	  <li>
	  	<%= link_to user.name, addList_path(:userid => user.id, :id => @list.id), class: 'shareName' %>
	  </li>
	<% end %>
</ul>

app/views/lists/show.html.erb
<% provide(:button_text, 'Add Item') %>

	<div class='listNameContainer'>
		<h1 class='listName'><%= @list.name %> </h1>
		<%=link_to "Share", shareList_path(:id => @list.id), class: 'buttonText' %>
	</div>
	<ul class="lists">
	<% @items.each do |item| %>
	  <li>
	  	<p  class='listTitle'><%= item.name %></p>
	  	<%=link_to "DELETE", deleteItem_path(:id => item.id), method: :delete, class: 'deleteButton' %>
	  </li>
	<% end %>
	</ul>

<%= render 'item_form' %>

app/views/static_pages/about.html.erb
<% provide(:title, ": About") %>

<h1>ABOUT</h1>

app/views/static_pages/friends.html.erb
<% provide(:title, ": Friends") %>

<h1>Friends</h1>

app/views/static_pages/help.html.erb
<% provide(:title, ": Help") %>

<h1>Help Page</h1>
<p>
  This is the Help page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/static_pages/home.html.erb
<h1 class='homeTitle'>List Share</h1>
<p class='homeDescription'>Create lists to keep track of to-dos, grocery lists, and anything else you need to keep track of. Share the lists with others to maintain the list together</p>

 <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary signup-button" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1 class='userName'><%= @user.name %></h1>
  <div class="col-md-8">
  	<%=link_to "New List", newList_path(:id => @user.id), class: 'buttonText' %>
    <% if @user.lists.any? %>
      <h3>lists (<%= @user.lists.count %>)</h3>
      <ul class="lists">
        <% @user.lists.each do |list| %>
		  <li>
        <%= link_to list.name, lists_path + '/' + list.id.to_s, class: 'listTitle' %>
		    <%=link_to "DELETE", deleteList_path(:id => list.id), method: :delete, class: 'deleteButton' %>
      </li>
		<% end %>
      </ul>
      <%= will_paginate @lists %>
    <% end %>
  </div>